# This is a basic workflow to help you get started with Actions

name: End-to-end tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: "http://localhost:3000"
        env:
          url: ${{ secrets.AUTH_URL}}
          auth_url: ${{ secrets.AUTH_URL}}
          auth_audience: ${{ secrets.AUTH_AUDIENCE}}
          auth_client_id: ${{ secrets.AUTH_CLIENT_ID}}
          auth_client_secret: ${{ secrets.AUTH_CLIENT_SECRET}}
          auth_username: ${{ secrets.AUTH_USERNAME}}
          auth_password: ${{ secrets.AUTH_PASSWORD}}
